name: weatha
description: A simple and user-friendly weather application which lets the users know the temperature of any location across the globe and also various parameters
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
#  -----------------------------------------------------------------------------------------
  connectivity_plus: ^4.0.0
  dio: ^5.1.2
  easy_localization: ^3.0.2
  fluttertoast: ^8.2.1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.6.0
  go_router: ^7.0.1
  permission_handler: ^10.2.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  universal_html: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - pubspec.yaml
