class LocalNames {
  final String pl,
      en,
      zh,
      it,
      de,
      he,
      cs,
      lt,
      ru,
      sr,
      hu,
      ro,
      tr,
      uk,
      et,
      ml,
      hr,
      ar,
      ku,
      eo,
      nl,
      fr,
      la,
      be,
      es,
      os,
      ko;

  LocalNames({
    required this.pl,
    required this.en,
    required this.zh,
    required this.it,
    required this.de,
    required this.he,
    required this.cs,
    required this.lt,
    required this.ru,
    required this.sr,
    required this.hu,
    required this.ro,
    required this.tr,
    required this.uk,
    required this.et,
    required this.ml,
    required this.hr,
    required this.ar,
    required this.ku,
    required this.eo,
    required this.nl,
    required this.fr,
    required this.la,
    required this.be,
    required this.es,
    required this.os,
    required this.ko,
  });
}
